//import com.example.assignment.domain.Employee

DROP TABLE IF EXISTS EMPLOYEES
DROP TABLE IF EXISTS DEPARTMENTS

CREATE TABLE EMPLOYEES(
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(100) UNIQUE,
    deptID FOREIGN KEY REFERENCES Department(ID),
    salary double
)

CREATE TABLE DEPARTMENTS (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(100) UNIQUE,
    minSalary INT,
    maxSalary INT
);